<?php

return [

    ["name" => "Play Station 5",
        "price" => 599.99,
        "image" => "https://upload.wikimedia.org/wikipedia/commons/0/03/PS5DigitalEdition.png",
        "description" => "La PlayStation 5 offre il massimo del gaming: grafica 4K, audio 3D, controller DualSense avanzato e una vasta libreria di giochi emozionanti. ",
    ],
    ["name" => "Iphone 15 Pro Max",
        "price" => 1739.00,
        "image" => "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-7inch-naturaltitanium?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1692845702708",
        "description" => "iPhone 15 Pro è il primo iPhone con un design in titanio di grado aerospaziale, la stessa lega usata per i veicoli inviati su Marte.",
    ],
    ["name" => "Nintendo Switch",
        "price" => 249.99,
        "image" => "https://www.carrefour.it/on/demandware.static/-/Sites-carrefour-master-catalog-IT/default/dw80c9d0b6/large/NINTENDOSWITCHCOLOR11-0045496452629-1.png",
        "description" => "Goditi l'esperienza completa di una console da casa, anche senza televisore. Nintendo Switch può trasformarsi, così troverai sempre dei momenti per giocare, anche quando sei impegnato. È una nuova era, in cui non è il tuo stile di vita a doversi adattare ai giochi, ma la tua console ad adattarsi al tuo stile di vita. Divertiti dove, quando e con chi vuoi!",
    ],
    ["name" => "Samsung Galaxy Z Flip 5",
        "price" => 1249.99,
        "image" => "https://images.samsung.com/is/image/samsung/p6pim/it/2307/gallery/it-galaxy-z-flip5-f731-468861-sm-f731blggeue-thumb-537458813?imwidth=480",
        "description" => "Acquista ora il nuovo smartphone pieghevole Samsung Galaxy Z Flip5 5G. Scopri gli sconti esclusivi per un periodo di tempo limitato.",
    ],
    ["name" => "HP 15-fc0014nl Notebook",
    "price" => 629.99,
    "image" => "https://www.hp.com/it-it/shop/Html/Merch/Images/c08484462_1750x1285.jpg",
    "description" => "Il PC laptop HP da 15,6 pollici, è ricco di funzionalità ed è la scelta perfetta per ogni budget, oltre ad essere più sostenibile per il pianeta. Costruito con materiali riciclati, questo potente laptop HP è dotato di processore AMD[1], ampio spazio di archiviazione e una grafica avanzata. Inoltre, il rapporto screen-to-body dell’85%[2] e la sottile cornice su tre lati offre tantissimo spazio per una visualizzazione straordinaria.",
    ],
    ["name" => "Xbox Series X",
    "price" => 549.99,
    "image" => "https://assets.xboxservices.com/assets/fb/7b/fb7bc68b-3fc7-4732-98f6-e5c3f3d10bf4.png?n=Consule-Hub_Content-Placement-0_SeriesX_740x555.png",
    "description" => "Xbox Series X offre una frequenza dei fotogrammi incredibilmente fluida, fino a 120 fps con il risalto visivo offerto dalla funzionalità HDR. Scopri mondi più luminosi, personaggi più definiti e dettagli incredibili con un 4K realistico.",
    ],
    ["name" => "Apple Watch Ultra 2",
    "price" => 909.00,
    "image" => "https://www.apple.com/it/apple-watch-ultra-2/images/overview/design/design_brighter_light__fw79yoz4yyaa_large.jpg",
    "description" => "L'/Apple Watch più robusto e versatile supera persino sé stesso. Con un innovativo SiP S9. Un nuovo, magico modo di usare l’orologio senza nemmeno toccarlo. Il display Apple più luminoso di sempre. E nuove combinazioni di cassa e cinturino a impatto ambientale neutro.",
    ],

];
